PREFIX=athena
include ../../../common/common.mk
include ../../../common/leaf.mk
#
# SERIALIZED_PB_OUTPUT_DIR := _pb_output
#
# .PHONY: install_requirements
# install_requirements:
# 	pip install -r requirements.txt
#
# .PHONY: serialize
# serialize: install_requirements
# 	pyflyte --config sandbox.config serialize workflows -f $(SERIALIZED_PB_OUTPUT_DIR)
