project_name: flytesnacks
builds:
  - skip: true
release:
  github:
    owner: evalsocket
    name: flytesnacks
  draft: false
  name_template: "{{.ProjectName}} v{{.Version}}"
  disable: false
  extra_files:
    - glob: ./cookbook/release-snacks/*
