# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  commands:
    - git clone https://www.github.com/flyteorg/flyte
    - cat flyte/monodocs-environment.lock.yaml
    - mamba install -c conda-forge conda-lock
    - conda-lock install -p /home/docs/monodocs-env flyte/monodocs-environment.lock.yaml
    - conda info
    - conda env list
    - cat flyte/docs/conf.py
    - cd flyte/docs && FLYTESNACKS_LOCAL_PATH=$PWD/../.. /home/docs/monodocs-env/bin/python -m sphinx -T -E -b html -d flyte/docs/_build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: flyte/docs/conf.py
