# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
    - pandoc
  jobs:
    pre_build:
      - pip install pypandoc
      - python ./cookbook/scripts/ipynb_to_gallery.py

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: cookbook/docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: cookbook/dev-requirements.txt
    - requirements: cookbook/docs-requirements.txt
