PREFIX=hive
include ../../common/Makefile.common

.PHONY: docker_build
docker_build: ;

.PHONY: docker_push
docker_push: ;
	
.PHONY: register_sandbox
register_sandbox: ;

.PHONY: serialize_sandbox
serialize_sandbox: ;

.PHONY: docker_push
docker_push: ;