PREFIX=image_spec_example

# GA workflow doesn't allow us to push images to the registry in the pull request, so we skip serializing this workflow
# in the CI. People can directly use `pyflyte run --remote image_spec_example.py wf` to run the example.

.PHONY: docker_build
docker_build: ;

.PHONY: docker_push
docker_push: ;

.PHONY: register
register: ;

.PHONY: serialize
serialize: ;

.PHONY: docker_push
docker_push: ;
