FROM python:3.11-slim-buster

MAINTAINER Flyte Team <users@flyte.org>
LABEL org.opencontainers.image.source https://github.com/flyteorg/flytekit

WORKDIR /root
ENV PYTHONPATH /root

RUN apt-get update && apt-get install build-essential git curl -y

RUN pip install flytekitplugins-deck-standard==1.8.0 rich marshmallow_enum
# RUN pip install --no-deps -U --force-reinstall "git+https://github.com/flyteorg/flyteidl.git@7aa32a59bae939e629cbcf12e85c096233028d38"
RUN pip install --no-deps -U --force-reinstall "git+https://github.com/flyteorg/flytekit.git@d90385a0e921a6a373ab80a9261949d45fbbad92"

