name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: false
      - name: Make Start
        shell: 'script -q -e -c "bash {0}"'
        run: make start
