name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - run: docker pull ghcr.io/flyteorg/flyte-sandbox:dind
      - name: Make Start
        shell: 'script -q -e -c "bash {0}"'
        run: |
          make setup wait fast_register
