name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - run: docker pull ghcr.io/flyteorg/flyte-sandbox:dind
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: false
      - name: Make Start
        shell: 'script -q -e -c "bash {0}"'
        run: |
          n = 0
          until ["$n" -ge 5]
          do
            echo "retry $n"
            make start && break
            n=$((n+1))
          done
