name: Build Examples

on:
  pull_request:
    
jobs:
  build-core:
    name: Build Core examples
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Push Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: latest,core-latest,core-${{ github.sha }},core-${{ github.event.ref }}
          push_git_tag: false
          push_image_and_stages: false
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:core-${{ github.sha }}"
          context: ./cookbook
          dockerfile: core/Dockerfile
  build-spark:
    name: Build spark plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: build Spark Plugin Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: k8s_spark-latest,k8s_spark-${{ github.sha }},k8s_spark-${{ github.event.ref }}
          push_git_tag: false
          push_image_and_stages: false
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:k8s_spark-${{ github.sha }}"
          context: ./cookbook/plugins
          dockerfile: k8s_spark/Dockerfile
  build-kfpytorch:
    name: Build Kfpytorch plugin example
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build Kubeflow Pytorch Plugin Docker Image 
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: kfpytorch-latest,kfpytorch-${{ github.sha }},kfpytorch-${{ github.event.ref }}
          push_git_tag: false
          push_image_and_stages: false
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:kfpytorch-${{ github.sha }}"
          context: ./cookbook/plugins
          dockerfile: kfpytorch/Dockerfile
  build-pandera:
    name: Build Pandera plugin example
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build Pandera Plugin Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: pandera-latest,pandera-${{ github.sha }},pandera-${{ github.event.ref }}
          push_git_tag: false
          push_image_and_stages: false
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:pandera-${{ github.sha }}"
          context: ./cookbook/plugins
          dockerfile: pandera/Dockerfile
  build-papermill:
    name: Build Papermill plugin example
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build Papermill Plugin Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: papermilltasks-latest,papermilltasks-${{ github.sha }},papermilltasks-${{ github.event.ref }}
          push_git_tag: false
          push_image_and_stages: false
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:papermilltasks-${{ github.sha }}"
          context: ./cookbook/plugins
          dockerfile: papermilltasks/Dockerfile
  build-pod:
    name: Build pod plugin example
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build Pod Plugin Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: pod-latest,pod-${{ github.sha }},pod-${{ github.event.ref }}
          push_git_tag: false
          push_image_and_stages: false
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:pod-${{ github.sha }}"
          context: ./cookbook/plugins
          dockerfile: pod/Dockerfile
  build-sagemaker-pytorch:
    name: Build SageMaker Pytorch Plugin example
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build SageMaker Pytorch Plugin Docker Image 
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: sagemaker_pytorch-latest,sagemaker_pytorch-${{ github.sha }},sagemaker_pytorch-${{ github.event.ref }}
          push_git_tag: false
          push_image_and_stages: false
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:sagemaker_pytorch-${{ github.sha }}"
          context: ./cookbook/plugins
          dockerfile: sagemaker_pytorch/Dockerfile
  build-sagemaker:
    name: Build Sagemaker plugin example
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build SageMaker Training Plugin Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: sagemaker_training-latest,sagemaker_training-${{ github.sha }},sagemaker_training-${{ github.event.ref }}
          push_git_tag: false
          push_image_and_stages: false
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:sagemaker_training-${{ github.sha }}"
          context: ./cookbook/plugins
          dockerfile: sagemaker_training/Dockerfile
  build-pima-diabetes:
    name: Build Pima Diabetes examples 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build Pima Diabetes Docker Image 
        uses: whoan/docker-build-with-cache-action@v5
        with:
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: pima_diabetes-latest,pima_diabetes-${{ github.sha }},pima_diabetes-${{ github.event.ref }}
          push_git_tag: false
          push_image_and_stages: false
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:pima_diabetes-${{ github.sha }}"
          context: ./cookbook/case_studies
          dockerfile: pima_diabetes/Dockerfile