name: Master

on:
  push:
    branches:
      - master
      - ci-overhaul
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  serialize_examples:
    runs-on: "ubuntu-latest"
    name: Serialize Flytesnacks workflow
    strategy:
      matrix:
        example: ["examples/k8s_spark_plugin"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements files
          key: ${{ format('{0}-pip-{1}', runner.os, hashFiles('dev-requirements.in', 'requirements.in')) }}
      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          pip install flytekitplugins-spark flytekitplugins-envd
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.FLYTE_BOT_USERNAME }}
          password: ${{ secrets.FLYTE_BOT_PAT }}
      - name: Pyflyte package
        run: |
          cd ${{ matrix.example }}
          pyflyte --pkgs k8s_spark_plugin package -o spark-package.tgz --force --fast
