name: Master

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  serialize_examples:
    runs-on: "ubuntu-latest"
    name: Serialize
    strategy:
      matrix:
        example:
          - advanced_composition
          - airflow_agent
          - k8s_spark_plugin
          - athena_plugin
          - aws_batch_plugin
          - basics
          - bigquery_agent
          - bigquery_plugin
          - blast
          - chatgpt_agent
          - customizing_dependencies
          - data_types_and_io
          - dbt_plugin
          - development_lifecycle
          - dolt_plugin
          - duckdb_plugin
          - exploratory_data_analysis
          - extending
          - feast_integration
          - forecasting_sales
          - greatexpectations_plugin
          - hive_plugin
          - house_price_prediction
          - k8s_dask_plugin
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements files
          key: ${{ format('{0}-pip-{1}', runner.os, hashFiles('dev-requirements.in', 'requirements.in')) }}
      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.in
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.FLYTE_BOT_USERNAME }}
          password: ${{ secrets.FLYTE_BOT_PAT }}
      - name: Pyflyte package
        run: |
          source .venv/bin/activate
          cd examples/${{ matrix.example }}
          pyflyte --pkgs ${{ matrix.example }} package -o spark-package.tgz --force --fast
