name: Build and Push Pima Diabetes Docker Images

on:
  pull_request:
  create:
    tags:
      - v*

jobs:
  push-github:
    name: Push Pima Diabetes examples to GHCR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cookbook
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Push Docker Image to Github Registry
        uses: whoan/docker-build-with-cache-action@v5
        with:
          # https://docs.github.com/en/packages/learn-github-packages/publishing-a-package
          username: "${{ secrets.FLYTE_BOT_USERNAME }}"
          password: "${{ secrets.FLYTE_BOT_PAT }}"
          image_name: ${{ github.repository_owner }}/flytecookbook
          image_tag: pima_diabetes-latest,pima_diabetes-${{ github.sha }},pima_diabetes-${{ github.event.ref }}
          push_git_tag: true
          registry: ghcr.io
          build_extra_args: "--compress=true --build-arg=tag=ghcr.io/${{ github.repository_owner }}/flytecookbook:pima_diabetes-${{ github.sha }}"
          context: ./cookbook/case_studies
          dockerfile: ml_training/pima_diabetes/Dockerfile
