name: Serialize & Register Examples

on:
  pull_request:
    paths-ignore:
      - 'cookbook/docs/**'
      - 'cookbook/deployment/**'
jobs:
  trigger-checks-flytesnacks-workflow:
    name: Serialize & Register Flytesnacks workflow
    uses: flyteorg/flytesnacks/.github/workflows/serialize_workflow.yml@master
    secrets:
      FLYTE_BOT_PAT: ${{ secrets.FLYTE_BOT_PAT }}
