name: Serialize snacks 

on:
  pull_request:

jobs:
  core-build:
    name: Build Core example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-core/
          key: release-snacks-core
      - name: Generate Serialize proto
        env:
          REGISTRY : "ghcr.io/flyteorg"
        run: |
          make -C cookbook/core serialize
  integrations-build:
    name: Build Integrations example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-integrations/
          key: release-snacks-plugins
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          make -C cookbook/integrations serialize
  case_studies-build:
    name: Build Case studies example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: actions/cache@v1
        with:
          path: /tmp/release-snacks-case-studies/
          key: release-snacks-case-studies
      - name: Generate Serialize proto
        env:
          REGISTRY: "ghcr.io/flyteorg"
        run: |
          make -C cookbook/case_studies serialize