name: Sandbox Register

on:
  pull_request:
    paths-ignore:
      - 'cookbook/docs/**'
      - 'cookbook/deployment/**'
    branches:
      - master

defaults:
  run:
    # https://github.com/actions/runner/issues/241#issuecomment-577360161
    shell: 'script -q -e -c "bash {0}"'

jobs:
  build:
    name: Sandbox Register
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: unionai/flytectl-setup-action@v0.0.1
      - name: setup sandbox
        run: flytectl sandbox start --sourcesPath=$GITHUB_WORKSPACE
      - name: fast register
        run: REGISTRY=ghcr.io/flyteorg VERSION=latest make fast_register