name: Build & Generate Documentation

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: cookbook

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch the code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f docs-requirements.txt ]; then pip install -r docs-requirements.txt; fi
      - name: Build the documentation
        run: |
          cd docs/
          sphinx-build -b html . _build
      - name: Tar HTML files
        run: tar -czvf docfiles.tar docs/_build/
      - name: Archive HTML files
        uses: actions/upload-artifact@v2
        with:
          name: docs-html-files
          path: cookbook/docfiles.tar
          retention-days: 2
